version: '3.3'
services:
  php:
    build:
      context: ./docker
    ports:
      - 9000:9000
    volumes:
      - ./php:/var/www/html
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  composer:
    image: "composer"
    volumes:
      - "./php:/app"
    command: install
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.2
    container_name: mysql
    restart: always
    volumes:
      - ./docker:/tmp/docker
    command: mysqld --init-file="/tmp/docker/db.sql"
    environment:
      - MYSQL_DATABASE=asker
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "8989:3306"
